apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-app
  namespace: dev-env
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
      - name: ai-container
        image: 587861061090.dkr.ecr.us-east-1.amazonaws.com/ai:tagversion
        ports:
        - containerPort: 3080
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: dev-env
spec:
  type: LoadBalancer
  selector:
    app: youtube
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3080
